// No magic numbers :)
const MORTAR_TRACE_JOB_ID: number = 283;
const WATERPROOFING_WALLS_JOB_ID: number = 537;
const HOT_WATER_RESERVOIR_INSTALLATION_JOB_ID: number = 523;
const CONCRETE_MIXING_OF_400L_IDLE_JOB_ID: number = 831;
const CONCRETE_MIXING_OF_400L_ACTIVE_JOB_ID: number = 830;

// Array containing job IDs that our component will iterate over to calculate the hierarchy of each job.
const jobIdArr: number[] = [
  MORTAR_TRACE_JOB_ID,
  WATERPROOFING_WALLS_JOB_ID,
  HOT_WATER_RESERVOIR_INSTALLATION_JOB_ID,
  CONCRETE_MIXING_OF_400L_IDLE_JOB_ID,
  CONCRETE_MIXING_OF_400L_ACTIVE_JOB_ID,
];

export {
  MORTAR_TRACE_JOB_ID,
  WATERPROOFING_WALLS_JOB_ID,
  HOT_WATER_RESERVOIR_INSTALLATION_JOB_ID,
  CONCRETE_MIXING_OF_400L_IDLE_JOB_ID,
  CONCRETE_MIXING_OF_400L_ACTIVE_JOB_ID,
  jobIdArr
};
